### ISSUE TITLE
DeleteOnVmDeletion does not seem to be sent for BSU

### ISSUE THREAD

**Issue by outscale-mdr** [outscale/osc-sdk-go#153]
I'm trying to create a VM with a Bsu that will be kept after the VM is deleted. Here is the [gists](https://gist.github.com/outscale-mdr/8f1ad2b767086cb339ab9ef19b22e8d4). When I do a ReadVms on the API, the DeleteOnVmDeletion is set to true.

I have tested on the v1.11.0 and the behavior is present but not on the v2.5.0

**Comment by jerome-jutteau** [comment]
Hi Maxime,

Thanks for the gist.
osc-cli test confirm the expected behavior so we can exclude an API bug.
Your example seems to confirm that this behavior is not expected.
We need to dig into this problem

**Comment by jerome-jutteau** [comment]
With traces enabled, I can confirm that `DeleteOnVmDeletion` is not populated in the request and it defaults to `True`.

Request sent in trace:
```json
{
  "BlockDeviceMappings": [
    {
      "Bsu": {
        "Iops": 3000,
        "VolumeSize": 10,
        "VolumeType": "io1"
      },
      "DeviceName": "/dev/xvdf"
    }
  ],
  "ImageId": "ami-b0d57010",
  "Performance": "standard",
  "Placement": {},
  "VmType": "tinav4.c1r1p1"
}
```
