### ISSUE TITLE
[Contribution] How to contribute?

### ISSUE THREAD

**Issue by Soulou** [outscale/osc-sdk-go#2]
Hello,

We'd like to contribute to this package, we can see most of the code is generated, how is it generated? Is there a way we could contribute to it?

Thanks,

**Comment by jerome-jutteau** [comment]
Hi,
We have a [CONTRIBUTING.md](https://github.com/outscale/osc-sdk-go/blob/master/CONTRIBUTING.md) file which explains few details.

Don't hesitate to open an issue before any change so we understand your need.
Thanks !

**Comment by Soulou** [comment]
Thanks a lot!
