### ISSUE TITLE
LoadBalancer Creation - OperationNotSupported (8010 - NotImplemented)

### ISSUE THREAD

**Issue by rchallie** [outscale/osc-sdk-go#860]
Hi !

Just tried to create a LoadBalancer using the SDK, following [this example](https://github.com/outscale/osc-sdk-go/blob/v2/examples/load_balancer_test.go), using the following code:

```golang
func (our *Outscale) DeployLoadBalancer(name string, lbtype string, listeners []Model.LoadBalancerListener) (*Model.LoadBalancer, error) {

        regions := []string{"eu-west-2a", "eu-west-2b"}
	outscaleListers := []OutscaleSDK.ListenerForCreation{}

	for _, listener := range listerners {
		outscaleListers = append(outscaleListers, OutscaleSDK.ListenerForCreation{
			BackendPort:          listener.BackendPort,
			LoadBalancerPort:     listener.LoadBalancerPort,
			LoadBalancerProtocol: listener.LoadBalancerProtocol,
		})
	}

	outscaleCreateLoadBalancerRequest := &OutscaleSDK.CreateLoadBalancerRequest{
		LoadBalancerName: name,
		SubregionNames:   &regions,
		Listeners:        outscaleListers,
		LoadBalancerType: &lbtype,
	}

	outscaleLoadBalancerResponse, httpRes, err := our.Client.LoadBalancerApi.
		CreateLoadBalancer(our.Context).
		CreateLoadBalancerRequest(*outscaleCreateLoadBalancerRequest).
		Execute()

	if err != nil {
		if httpRes != nil {
			our.OutputHttpError("LoadBalancer", *httpRes)
		}
		return nil, err
	}
	
	[...]
}
```
where:
- `our` is a custom Structure
- `listeners` is a custom Structure

with following parameters:
- `name`: "LB-TEST"
- `lbtype`: "internet-facing"
- `listeners`: `[]{ {BackendPort: int32(443), LoadBalancerPort: int32(443), LoadBalancerProtocol:"HTTPS"} }`

<hr>

I got the following response:
```json
{
  "Errors": [
    {
      "Type": "OperationNotSupported",
      "Details": "",
      "Code": "8010"
    }
  ],
  "ResponseContext": {
    "RequestId": "<request_id>"
  }
}
```

Is that normal or did I do something wrong ?
Thanks !

**Comment by jerome-jutteau** [comment]
Hi @rchallie 

Unfortunately, `OperationNotSupported` is an API error.

```go
regions := []string{"eu-west-2a", "eu-west-2b"}
```

Load Balancers can load balance traffic to several AZ but must currently be created on only one specific AZ. `SubregionNames ` array should only contain one item for now.
Also note that a Load Balancer is identified through its name which is scoped to your account. This mean that you cannot create two Load Balancers named `LB-TEST` on your account.
To avoid eventual collision with old resources, a common practice is to generate name with a random or unique part (like `my-project-1675697760` where `1675697760` is epoch time) 

You can have more details about Load Balancers in [Outscale documentation](https://docs.outscale.com/en/userguide/About-Load-Balancers.html)

**Comment by rchallie** [comment]
Hi @jerome-jutteau 

With only one AZ it work and changing LoadBalancer name, it works.

Thank you for your reply and your precisions !
